version: '3'
services:

  postgres:
    build: docker/postgres
    container_name: postgres
    ports:
      - '5432:5432'

  app:
    build: ./
    container_name: java
    ports:
      - '8080:8080'